### ISSUE TITLE
error with preprocess_binary_file

### ISSUE THREAD

**Issue by mariehemelt** [m-beau/NeuroPyxels#199]
I'm getting this error when I run preprocess_binary_file after the preprocessing is run:
 
 can't invoke "event" command: application has been destroyed
    while executing
"event generate $w <<ThemeChanged>>"
    (procedure "ttk::ThemeChanged" line 6)
    invoked from within
"ttk::ThemeChanged"

Not sure what this is or if it is important.

This is the exact command

filtered_fname = preprocess_binary_file(dp, filt_key='ap', fname=None, target_dp=None, move_orig_data=True, median_subtract=True, f_low=None, f_high=300, order=3, verbose=True)

Only seems to happen sometimes! Thanks.

**Comment by m-beau** [comment]
Hey Marie, did recent patches fix your issue?
