### ISSUE TITLE
Permission error on ubuntu VM

### ISSUE THREAD

**Issue by mariehemelt** [m-beau/NeuroPyxels#208]
I am installing Neuropyxels on a ubuntu VM on our windows server. I am getting this permission error when I try to run the filtering algorithm:

iltered_fname = preprocess_binary_file(dp, filt_key='ap', fname=None, target_dp=None, move_orig_data=False, median_subtract=True, f_low=None, f_high=300, order=3, verbose=True)
Preprocessing /home/mh553@dhe.duke.edu/Ddrive/MarieQD/DH12_211201g2/DH12_21_12_01_g2_t0.imec0.ap.bin...
    - median subtraction (aka common average referencing CAR),
    - filtering in time (between 0 and 300 Hz) forward:True, backward:False.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mh553@dhe.duke.edu/NeuroPyxels/npyx/inout.py", line 812, in preprocess_binary_file
    with open(target_dp / filtered_fname, 'wb') as fw:  # open for writing processed data
PermissionError: [Errno 13] Permission denied: '/home/mh553@dhe.duke.edu/Ddrive/MarieQD/DH12_211201g2/DH12_21_12_01_g2_t0.imec0_medsub_tempfiltNone300TrueFalse.ap.bin'

Any help appreciated! We ran into a very niche permission error when I was running this on the windows side, but because of GPU issues we had to switch to this ubuntu VM.

**Comment by m-beau** [comment]
Hi Marie,

Do you run your script from a jupyter notebook, or a python script from the terminal?

**Comment by mariehemelt** [comment]
Python script from the terminal

**Comment by m-beau** [comment]
All right - can you run it with sudo then?

**Comment by mariehemelt** [comment]
I tried two different ways and got these errors.
dp = Path('/home/mh553@dhe.duke.edu/Ddrive/MarieQD/DH12_211201g2')
>>> sudo /home/mh553@dhe.duke.edu/Ddrive/MarieQD/DH12_211201g2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sudo' is not defined
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
(Npyx) mh553@NB-UBUNTU-VM:~/NeuroPyxels$ sudo python
[sudo] password for mh553: 
sudo: python: command not found
