### ISSUE TITLE
Sampling rate from metadata converted to int

### ISSUE THREAD

**Issue by nazgulfg92** [m-beau/NeuroPyxels#352]
Hi all,
First of all, thanks for the wonderful package!
I was fiddling around with loading some metadata from a recording and realised that the sampling rate returned from the `npyx.inout.metadata` function is converted to int (line 262 in the code):

```
            if meta_glx[filt_key]['typeThis'] == 'imec':
                meta[filt_key]['sampling_rate']=int(meta_glx[filt_key]['imSampRate'])
```

If, by some circumstances, one has more than one event, wouldn't this lead to accumulated error? The calibrated sampling rate from my recording is 30000.352941 (which is the sampling rate `.meta` file), but from the `metadata` function I'd get 30000.

Ultimately, I worry that it might make event detection (e.g. from the sync channel) a little bit inaccurate (although the error would be very small, almost negligible).

**Comment by m-beau** [comment]
The master branch is now fixed. Bear in mind that the pip uploaded version of the package is not yet! I will update it soon.

**Comment by nazgulfg92** [comment]
Great! Thanks a lot!
I noticed something else in the output of the `get_npix_sync` function; I'll open another issue to let you know in more detail :)
