### ISSUE TITLE
Issue with the outputs of get_npix_sync

### ISSUE THREAD

**Issue by nazgulfg92** [m-beau/NeuroPyxels#354]
Hi!

I noticed somethign with the outputs of `npyx.inout.get_npix_sync`. If calculating the the onset (or offset) times using some `filt_key` value (e.g.  `filt_key = 'highpass'`) everything works quite well on the first pass. As I understand it, if I wanna retrieve that information a second time, the function tries to find if this was already calculated from before and loads it from the file it created on the first run (in the folder `sync_chan`)

Now let's say I try to run the function with `filt_key = 'lowpass'` on the second time (using 'highpass' the first). On the second run, the onset times come out wrong, most likely because the function calculates them using the sampling rate previously saved (taken from the AP band used in the first run with `filt_key = 'highpass'`). The analysis is not interchangeable between `filt_key` values, and would return proper onset or offset times only if always using the same `filt_key` stored int the files it creates. Otherwise it converts from samples to time using a wrong sampling rate.

**Comment by m-beau** [comment]
Hmm I haven't done extensive testing with lfp files so it is very possible that a bug sneaked in somewhere - are you using spkeGLX or openEphys?

**Comment by m-beau** [comment]
Awesome!
