### ISSUE TITLE
Can't read Neuropixels Ultra SpikeGLX metadata

### ISSUE THREAD

**Issue by stephen-kyranakis** [m-beau/NeuroPyxels#378]
read_metadata fails with a Neuropixels Ultra SpikeGLX metadata file. I first get "WARNING probe version 1123.0 not handled - post an issue at www.github.com/m-beau/NeuroPyxels", and then I get the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u239257\Anaconda3\envs\phyllum_cell_type_classifier\lib\site-packages\npyx\inout.py", line 48, in read_metadata
    meta = metadata(dp)
  File "C:\Users\u239257\Anaconda3\envs\phyllum_cell_type_classifier\lib\site-packages\npyx\inout.py", line 241, in metadata
    meta['bit_uV_conv_factor']=(Vrange/2**bits_encoding/ampFactor)
UnboundLocalError: local variable 'bits_encoding' referenced before assignment

The variable bits_encoding is not set because the probe version isn't one of the four recognized ones. I'm using the cell_type_classifier branch, but as far as I can tell, the relevant code seems identical in the master and m-beau branches.

**Comment by stephen-kyranakis** [comment]
"imDatPrb_type=1123"

If it helps, I see the same number in this other line: "imDatPrb_pn=NP1123"

Thanks for your help!

**Comment by m-beau** [comment]
Ok this is a new format of imec meta files currently not handled by npyx. Can you share the spikeGLX version with me please, and your probe type? Is this a 1.0, or 2.0?

**Comment by stephen-kyranakis** [comment]
SpikeGLX v.20230815, Imec phase30 v3.62
Probe type: NP1123

**Comment by m-beau** [comment]
Thanks for the imec version - for the probe version, I literally meant: is it a 1.0 or a 2.0? Is the vertical spacing between your channels 20um, or 15um?

**Comment by asanlop** [comment]
This probe type is referred as UHD3, the specific model NP1123 consist on a 12x32 matrix of contacts located at the tip of the probe. The contacts size is 3.5 x 3.5 um with a pitch between rows and columns of 4.5 um.

Thanks for your help.

**Comment by m-beau** [comment]
Right you have an ultra! Send me your ap.meta file (you can email me at "m period beau 047 at gmail period com") and I'll implement it asap.

**Comment by asanlop** [comment]
Thanks, this has been solved and it can process Neuropixels ultra now.

**Comment by m-beau** [comment]
Awesome!
