### ISSUE TITLE
How to change cache location?

### ISSUE THREAD

**Issue by chris-angeloni** [m-beau/NeuroPyxels#384]
By default the cache location is in my home folder (User/chris) on the C: drive. However, as my cache grows as I analyze more datasets, it is filling my C: drive. Is there a way to modify the cache location to a larger drive?

**Comment by m-beau** [comment]
Hi Chris,

Yes I realized this could become a problem, I am in the process of completely getting rid of my 'home-made caching' inherited form a time when I didn't know better to replace it with joblib - I will implement this feature asap, and have the default be in the same directory of the dataset. It would distribute the data more.

**Comment by chris-angeloni** [comment]
Sounds exciting! In the meantime a hacky way for me to get around this would be to change the path in `cachedir = Path(op.expanduser("~")) / ".NeuroPyxels"` in the import section of a bunch of functions?

**Comment by m-beau** [comment]
Implemented in the last PR (not yet available on pip, only on the git master branch - I want to make sure it doesn't break anything for a bit longer)!

You can now simply edit the directory in .../npyx/CONFIG.py, which is `__cachedir__ = "~/.NeuroPyxels"` by default, with any path.

I would stick to a fast SSD though!

**Comment by m-beau** [comment]
FYI, I implemented a solution (turned it into a python package because it turned out to be much more work than anticipated): https://github.com/m-beau/cachecache

Testing it for a couple of weeks before pushing it to the master branch.
