### ISSUE TITLE
Unable to read spikeGLX metadata

### ISSUE THREAD

**Issue by Andrianarivelo** [m-beau/NeuroPyxels#394]
Hi Maxime, 

First time using your tool which is great ! However I ran into an error when running` test_npyx(dp, raise_error=True)`
I have no idea if I messed up a step but I thinks its just that the inout script metadata reading part is outdated for spikeglx especially for the probe version (I guess now in imDatPrb_type, imDatPrb_type=2013 for 2.0 4 shanks)
Attached images of the issue, content of new metadata file.

Any help is welcome.
![metadata_issues](https://github.com/m-beau/NeuroPyxels/assets/70333713/62f51311-319c-4b60-8f40-21d3a84bf4d9)
![inout_metadata](https://github.com/m-beau/NeuroPyxels/assets/70333713/ba019a76-b6ae-45b9-ac76-57ba0b66b6d6)
![glx_metadata](https://github.com/m-beau/NeuroPyxels/assets/70333713/d9bac870-8329-421a-ad03-a914755f7d5f)

Best, 
Andry

**Comment by m-beau** [comment]
Hey Andri,

Sorry for the late reply, I was away after my PhD graduation!

Indeed you found the problem, I never encountered this probe version in the past (2013). Can you tell me whether you were using a 1.0, 2.0...? I will add this version in.

Cheers,
Maxime

**Comment by melkalliny** [comment]
Same issue here. Using the commercially available 2.0 4-shank w/ silicone cap, and probe version is 2013.0. Able to manually treat it as a '2.0_fourshanks' for now.

**Comment by m-beau** [comment]
FYI I have just pushed a version on NeuroPyxels that should handle most probe types out there.

Let me know if it keeps not working for you.

**Comment by m-beau** [comment]
I'll assume that this solved your problem! Closing this issue.
