### ISSUE TITLE
Probe version 2013.0 not handled

### ISSUE THREAD

**Issue by vdtang3** [m-beau/NeuroPyxels#400]
Hi - I'm getting an error while trying to analyze data collected using a 4 shank NP2.0 due to the probe version not being handled. Would it be possible to add support for this probe? Per the error statement, I've attached an example .meta file, although the ap and lfp bands are combined in these new probes.
[example_meta_file.zip](https://github.com/user-attachments/files/17911490/example_meta_file.zip)

Thanks,
Vincent

**Comment by m-beau** [comment]
Hi Vincent,

No worries, will implement your version asap. Thanks for bringing it up.

**Comment by vdtang3** [comment]
Everything looks to be working, thanks so much!
